branch-defaults:
  default:
    environment: ExamClock-dev
  server:
    environment: ExamClock-dev
global:
  application_name: Exam Clock
  default_ec2_keyname: ExamClockSSHKey
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-deploy-user
  sc: git
  workspace_type: Application